# Создаем новые переменные

In [1]:
import pandas as pd

bikes = pd.read_csv('BikeData.csv')
bikes.head()

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38

In [7]:
bikes['Rental Count'] = bikes['Partner 1'] + bikes['Partner 2']
bikes['Rental Count']

0        257
1        219
2        162
3        148
4         97
        ...
8755     644
8756     359
8757    1236
8758     628
8759     843
Name: Rental Count, Length: 8760, dtype: int64

In [13]:
# bikes = bikes.drop('Partner 1', axis=1)
bikes = bikes.drop('Partner 2', axis=1)
bikes

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Rental Count
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

In [15]:
pd.to_datetime(bikes['Date'], format="%d/%m/%Y").dt.month

0       12
1       12
2       12
3       12
4       12
        ..
8755    11
8756    11
8757    11
8758    11
8759    11
Name: Date, Length: 8760, dtype: int32

In [17]:
pd.to_datetime(bikes['Date'], format="%d/%m/%Y").dt.month

0       12
1       12
2       12
3       12
4       12
        ..
8755    11
8756    11
8757    11
8758    11
8759    11
Name: Date, Length: 8760, dtype: int32

In [19]:
bikes['Date'] = pd.to_datetime(bikes['Date'], format="%d/%m/%Y")

In [20]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8760 non-null   datetime64[ns]
 1   Hour             8760 non-null   int64
 2   Temperature      8581 non-null   float64
 3   Humidity         8760 non-null   int64
 4   Wind speed       8760 non-null   float64
 5   Rainfall         8760 non-null   float64
 6   Snowfall         8760 non-null   float64
 7   Seasons          8760 non-null   object
 8   Holiday          8760 non-null   object
 9   Functioning Day  8760 non-null   object
 10  Rental Count     8760 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(3), object(3)
memory usage: 752.9+ KB

In [22]:
bikes['Date'].dt.month

0       Friday
1       Friday
2       Friday
3       Friday
4       Friday
         ...
8755    Friday
8756    Friday
8757    Friday
8758    Friday
8759    Friday
Name: Date, Length: 8760, dtype: object

In [ ]:
bikes['Date'].dt.year

In [ ]:
bikes[bikes['Date'].dt.year == 2017].shape

In [ ]:
bikes[bikes['Date'].dt.year == 2018].shape

In [ ]:
bikes['Date'].dt.day_name()

In [ ]:
bikes[bikes['Date'].dt.day_name() == 'Sunday'].shape

In [25]:
bikes['Functioning Day'] = bikes['Functioning Day'] == 'Yes'
bikes['Functioning Day']

0       False
1       False
2       False
3       False
4       False
        ...
8755    False
8756    False
8757    False
8758    False
8759    False
Name: Functioning Day, Length: 8760, dtype: bool

### Вспоминаем про функции

In [26]:
def currency_converter(rub):
    return round(rub / 74.73,2)

currency_converter(1000)

13.38

In [27]:
amounts = [1000, 2000, 4214, 12321]
print(list(map(currency_converter, amounts)))
print(list(map(lambda x: round(x / 74.73,2), amounts)))
print(list(map(lambda x: 0 if x < 3000 else 1, amounts)))

[13.38, 26.76, 56.39, 164.87]
[13.38, 26.76, 56.39, 164.87]
[0, 0, 1, 1]

In [28]:
bikes['Holiday'].apply(lambda x: 1 if x == 'Holiday' else 0).sum()

432

In [29]:
bikes[bikes['Holiday'] == 'Holiday'].shape

(432, 11)

In [ ]:
bikes['Holiday'] = bikes['Holiday'].apply(lambda x: 1 if x == 'Holiday' else 0)

In [39]:
bikes.head()

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Rental Count,Temperature Category
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,False,257,Freezing
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,False,219,Freezing
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,False,162,Freezing
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,False,148,Freezing
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,False,97,Freezing

In [40]:
bikes['Normal Humidity'] = bikes['Humidity'].apply(lambda x: 1 if x in range(40,61) else 0)

In [41]:
def get_temp_cat(temp):
    if temp < 0:
        return 'Freezing'
    elif temp < 15:
        return 'Chilly'
    elif temp < 26:
        return 'Nice'
    elif temp >= 26:
        return 'Hot'
    else:
        return temp

In [42]:
bikes['Temperature Category'] = bikes['Temperature'].apply(get_temp_cat)

In [43]:
bikes[['Temperature Category', 'Temperature']].tail()

     Temperature Category  Temperature
8755               Chilly          4.2
8756               Chilly          3.4
8757               Chilly          2.6
8758               Chilly          2.1
8759               Chilly          1.9

In [44]:
bikes['Temperature Category'] = pd.Categorical(bikes['Temperature Category'])

In [45]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  8760 non-null   datetime64[ns]
 1   Hour                  8760 non-null   int64
 2   Temperature           8581 non-null   float64
 3   Humidity              8760 non-null   int64
 4   Wind speed            8760 non-null   float64
 5   Rainfall              8760 non-null   float64
 6   Snowfall              8760 non-null   float64
 7   Seasons               8760 non-null   object
 8   Holiday               8760 non-null   object
 9   Functioning Day       8760 non-null   bool
 10  Rental Count          8760 non-null   int64
 11  Temperature Category  8581 non-null   category
 12  Normal Humidity       8760 non-null   int64
dtypes: bool(1), category(1), datetime64[ns](1), float64(4), int64(4), object(2)
memory usage: 770.2+ KB

In [46]:
bikes['Temperature Category'].cat.codes

0       1
1       1
2       1
3       1
4       1
       ..
8755    0
8756    0
8757    0
8758    0
8759    0
Length: 8760, dtype: int8

In [47]:
bikes['Temperature Category'].cat.categories

Index(['Chilly', 'Freezing', 'Hot', 'Nice'], dtype='object')

In [48]:
import numpy as np

bikes['Good Weather'] = np.where((bikes['Temperature Category'] == 'Nice') &
         (bikes['Normal Humidity'] == 1) &
         (bikes['Wind speed'] <= 5.4) &
         (bikes['Snowfall'] == 0) &
         (bikes['Rainfall'] == 0), 1, 0)

In [49]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  8760 non-null   datetime64[ns]
 1   Hour                  8760 non-null   int64
 2   Temperature           8581 non-null   float64
 3   Humidity              8760 non-null   int64
 4   Wind speed            8760 non-null   float64
 5   Rainfall              8760 non-null   float64
 6   Snowfall              8760 non-null   float64
 7   Seasons               8760 non-null   object
 8   Holiday               8760 non-null   object
 9   Functioning Day       8760 non-null   bool
 10  Rental Count          8760 non-null   int64
 11  Temperature Category  8581 non-null   category
 12  Normal Humidity       8760 non-null   int64
 13  Good Weather          8760 non-null   int64
dtypes: bool(1), category(1), datetime64[ns](1), float64(4), int64(5), object(2)
memory usage: 838.7+ KB

In [52]:
bikes.to_pickle('BikesDataVars.pkl')

In [53]:
bikes.to_csv('BikesDataVars.csv', index=False)
bikes.to_excel('BikesDataVars.xlsx', index=False)

In [55]:
df_pkl = pd.read_pickle('BikesDataVars.pkl')

In [56]:
df_pkl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  8760 non-null   datetime64[ns]
 1   Hour                  8760 non-null   int64
 2   Temperature           8581 non-null   float64
 3   Humidity              8760 non-null   int64
 4   Wind speed            8760 non-null   float64
 5   Rainfall              8760 non-null   float64
 6   Snowfall              8760 non-null   float64
 7   Seasons               8760 non-null   object
 8   Holiday               8760 non-null   object
 9   Functioning Day       8760 non-null   bool
 10  Rental Count          8760 non-null   int64
 11  Temperature Category  8581 non-null   category
 12  Normal Humidity       8760 non-null   int64
 13  Good Weather          8760 non-null   int64
dtypes: bool(1), category(1), datetime64[ns](1), float64(4), int64(5), object(2)
memory usage: 838.5+ KB

In [57]:
df_csv = pd.read_csv('BikesDataVars.csv')
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  8760 non-null   object
 1   Hour                  8760 non-null   int64
 2   Temperature           8581 non-null   float64
 3   Humidity              8760 non-null   int64
 4   Wind speed            8760 non-null   float64
 5   Rainfall              8760 non-null   float64
 6   Snowfall              8760 non-null   float64
 7   Seasons               8760 non-null   object
 8   Holiday               8760 non-null   object
 9   Functioning Day       8760 non-null   bool
 10  Rental Count          8760 non-null   int64
 11  Temperature Category  8581 non-null   object
 12  Normal Humidity       8760 non-null   int64
 13  Good Weather          8760 non-null   int64
dtypes: bool(1), float64(4), int64(5), object(4)
memory usage: 898.4+ KB

In [58]:
df_xlsx = pd.read_excel('BikesDataVars.xlsx', index_col=False)
df_xlsx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  8760 non-null   datetime64[ns]
 1   Hour                  8760 non-null   int64
 2   Temperature           8581 non-null   float64
 3   Humidity              8760 non-null   int64
 4   Wind speed            8760 non-null   float64
 5   Rainfall              8760 non-null   float64
 6   Snowfall              8760 non-null   float64
 7   Seasons               8760 non-null   object
 8   Holiday               8760 non-null   object
 9   Functioning Day       8760 non-null   bool
 10  Rental Count          8760 non-null   int64
 11  Temperature Category  8581 non-null   object
 12  Normal Humidity       8760 non-null   int64
 13  Good Weather          8760 non-null   int64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(5), object(3)
memory usage: 898.4+ KB